name: CI
on: push
#  push:
#    branches:
#      - *
#  pull_request:
#    branches:
#      - main

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      PROJECT_VERSION: 1.0.0
      PROJECT_BUILD: 3
      CERTIFICATES_P12: ${{ secrets.CERTIFICATES_P12 }}
      CERTIFICATES_P12_PASSWORD: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      CERTIFICATES_P12_PATH: $RUNNER_TEMP/Certificates.p12
      MOBILE_PROVISION: ${{ secrets.MOBILE_PROVISION }}
      MOBILE_PROVISION_NAME: ${{ secrets.MOBILE_PROVISION_NAME }}
      MOBILE_PROVISION_PATH: ~/Library/MobileDevice/Provisioning\ Profiles/$MOBILE_PROVISION_NAME
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      KEYCHAIN_PATH: $RUNNER_TEMP/app-signing.keychain-db
      EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
      EXPORT_OPTIONS_PLIST_PATH: $RUNNER_TEMP/ExportOptions.plist
      ICLOUD_USERNAME: ${{ secrets.ICLOUD_USERNAME }}
      ICLOUD_PASSWORD: ${{ secrets.ICLOUD_PASSWORD }}
    steps:
      - name: Check Xcode Version
        run: xcodebuild -version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: |
          echo -n $EXPORT_OPTIONS_PLIST > $EXPORT_OPTIONS_PLIST_PATH && \
          echo -n $CERTIFICATES_P12 | base64 --decode > $CERTIFICATES_P12_PATH && \
          echo -n $MOBILE_PROVISION | base64 --decode > $MOBILE_PROVISION_PATH && \
          security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH && \
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH && \
          security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH && \
          security import $CERTIFICATES_P12_PATH -P $CERTIFICATES_P12_PASSWORD -A -t cert -f pkcs12 -k $KEYCHAIN_PATH && \
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Build for iOS
        run: |
          yarn install && \
          xcodebuild -workspace ios/example.xcworkspace \
            -scheme example \
            -configuration Release \
            clean && \
          xcodebuild -workspace ios/example.xcworkspace \
            -scheme "example" \
            -sdk iphoneos \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath $RUNNER_TEMP/example.xcarchive \
            ONLY_ACTIVE_ARCH=NO \
            ENABLE_BITCODE=NO \
            VALID_ARCHS="arm64 arm64e armv7s" \
            MARKETING_VERSION=$PROJECT_VERSION \
            CURRENT_PROJECT_VERSION=$PROJECT_BUILD \
            archive && \
          xcodebuild -exportArchive \
            -archivePath $RUNNER_TEMP/example.xcarchive \
            -exportOptionsPlist $EXPORT_OPTIONS_PLIST_PATH \
            -exportPath $RUNNER_TEMP && \
          xcrun altool --upload-app \
            --file $RUNNER_TEMP/example.ipa \
            --type ios \
            --username $ICLOUD_USERNAME \
            --password $ICLOUD_PASSWORD
