name: CI
on: push
#  push:
#    branches:
#      - *
#  pull_request:
#    branches:
#      - main

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      MARKETING_VERSION: 1.0.0
      PROJECT_BUILD: 3
      BUILD_PATH: ios/build
      CERTIFICATES_P12: ${{ secrets.CERTIFICATES_P12 }}
      CERTIFICATES_P12_PASSWORD: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      CERTIFICATES_P12_PATH: $BUILD_PATH/Certificates.p12
      EMBEDDED_MOBILEPROVISION: ${{ secrets.EMBEDDED_MOBILEPROVISION }}
      EMBEDDED_MOBILEPROVISION_PATH: $BUILD_PATH/embedded.mobileprovision
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      KEYCHAIN_PATH: $BUILD_PATH/keychain.db
      EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
      EXPORT_OPTIONS_PLIST_PATH: $BUILD_PATH/ExportOptions.plist
    steps:
      - name: Check Xcode Version
        run: xcodebuild -version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: |
          mkdir -p $BUILD_PATH && \
          echo -n $EXPORT_OPTIONS_PLIST > EXPORT_OPTIONS_PLIST_PATH && \
          echo -n $CERTIFICATES_P12 | base64 --decode > $CERTIFICATES_P12_PATH && \
          echo -n $EMBEDDED_MOBILEPROVISION | base64 --decode > $EMBEDDED_MOBILEPROVISION_PATH && \
          security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH && \
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH && \
          security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH && \
          security import $CERTIFICATES_P12_PATH -P $CERTIFICATES_P12_PASSWORD -A -t cert -f pkcs12 -k $KEYCHAIN_PATH && \
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Build for iOS
        run: |
          yarn install && \
          xcodebuild -workspace ios/example.xcworkspace \
          -scheme example \
          -configuration Release \
          clean && \
          xcodebuild -workspace ios/example.xcworkspace \
          -scheme "example" \
          -sdk iphoneos \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath $BUILD_PATH/example.xcarchive \
          ONLY_ACTIVE_ARCH=NO \
          ENABLE_BITCODE=NO \
          VALID_ARCHS="arm64 arm64e armv7s" \
          MARKETING_VERSION=$MARKETING_VERSION \
          CURRENT_PROJECT_VERSION=$PROJECT_BUILD \
          archive