name: CI
on: push
#  push:
#    branches:
#      - *
#  pull_request:
#    branches:
#      - main

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      CERTIFICATES_P12: ${{ secrets.CERTIFICATES_P12 }}
      CERTIFICATES_P12_PASSWORD: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      EMBEDDED_MOBILEPROVISION: ${{ secrets.EMBEDDED_MOBILEPROVISION }}
      EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      BUILD_PATH: 'ios/build'
      EXPORT_OPTIONS_PLIST_PATH: 'ios/build/ExportOptions.plist'
      MARKETING_VERSION: 1.0.0
      PROJECT_BUILD: 3
    steps:
      - name: Check Xcode Version
        run: xcodebuild -version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: |
          mkdir -p $BUILD_PATH && \
          echo $EXPORT_OPTIONS_PLIST > EXPORT_OPTIONS_PLIST_PATH

      - name: Build for iOS
        run: |
          yarn install && \
          xcodebuild -workspace ios/example.xcworkspace \
          -scheme example \
          -configuration Release \
          clean && \
          xcodebuild -workspace ios/example.xcworkspace \
          -scheme "example" \
          -sdk iphoneos \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath $BUILD_PATH/example.xcarchive \
          ONLY_ACTIVE_ARCH=NO \
          ENABLE_BITCODE=NO \
          VALID_ARCHS="arm64 arm64e armv7s" \
          MARKETING_VERSION=$MARKETING_VERSION \
          CURRENT_PROJECT_VERSION=$PROJECT_BUILD \
          archive