name: CI
on: push
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      PROJECT_VERSION: 1.0.0
      PROJECT_BUILD: 3
      BUILD_PATH: ios/build
      CERTIFICATES_P12: ${{ secrets.CERTIFICATES_P12 }}
      CERTIFICATES_P12_PASSWORD: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      CERTIFICATES_P12_PATH: ios/build/Certificates.p12
      MOBILE_PROVISION: ${{ secrets.MOBILE_PROVISION }}
      MOBILE_PROVISION_PATH: ios/build/embedded.mobileprovision
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      KEYCHAIN_PATH: ios/build/app-signing.keychain-db
      EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
      EXPORT_OPTIONS_PLIST_PATH: ios/build/ExportOptions.plist
      ICLOUD_USERNAME: ${{ secrets.ICLOUD_USERNAME }}
      ICLOUD_PASSWORD: ${{ secrets.ICLOUD_PASSWORD }}
    steps:
      - name: Check Xcode Version
        run: xcodebuild -version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: |
          mkdir -p $BUILD_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTIONS_PLIST_PATH
          echo -n "$CERTIFICATES_P12" | base64 --decode -o $CERTIFICATES_P12_PATH
          echo -n "$MOBILE_PROVISION" | base64 --decode -o $MOBILE_PROVISION_PATH
          cp -f $MOBILE_PROVISION_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          security create-keychain -p $KEYCHAIN_PASSWORD `pwd`/$KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 `pwd`/$KEYCHAIN_PATH
          security unlock-keychain -p $KEYCHAIN_PASSWORD `pwd`/$KEYCHAIN_PATH
          security import $CERTIFICATES_P12_PATH -P $CERTIFICATES_P12_PASSWORD -A -t cert -f pkcs12 -k `pwd`/$KEYCHAIN_PATH
          security list-keychain -d user -s `pwd`/$KEYCHAIN_PATH

      - name: Resolve Dependencies
        run: |
          yarn install
          cd ios
          pod install
          cd ..
      
      - name: Clean
        run: |
          xcodebuild -workspace ios/example.xcworkspace \
            -scheme example \
            -configuration Release \
            clean
      
      - name: Archive
        run: |
          xcodebuild -workspace ios/example.xcworkspace \
            -scheme "example" \
            -sdk iphoneos \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath $BUILD_PATH/example.xcarchive \
            ONLY_ACTIVE_ARCH=NO \
            ENABLE_BITCODE=NO \
            VALID_ARCHS="arm64 arm64e armv7s" \
            MARKETING_VERSION=$PROJECT_VERSION \
            CURRENT_PROJECT_VERSION=$PROJECT_BUILD \
            archive
      
      - name: Export
        run: |
          xcodebuild -exportArchive \
            -archivePath $BUILD_PATH/example.xcarchive \
            -exportOptionsPlist $EXPORT_OPTIONS_PLIST_PATH \
            -exportPath $BUILD_PATH && \
      
      - name: Upload
        run: |
          xcrun altool --upload-app \
            --file $BUILD_PATH/example.ipa \
            --type ios \
            --username $ICLOUD_USERNAME \
            --password $ICLOUD_PASSWORD
